---

- name: Configure Kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: kibana
    group: kibana
    mode: 0750
  notify: restart kibana

- name: Installing X-Pack to Kibana
  shell: yes | ./bin/kibana-plugin install x-pack
  args:
    chdir: /usr/share/kibana
    creates: /usr/share/kibana/plugins/x-pack/package.json
  become: yes
  become_user: kibana
  notify: restart kibana
  when: {{ elk_kibana_xpack }}
