---

- name: Configure Logstash
  template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml
    owner: logstash
    group: logstash
    mode: 0750
  notify: restart logstash

- name: Configure Logstash | local-syslog-input
  template:
    src: logstash/05-local-syslog-input.conf.j2
    dest: /etc/logstash/conf.d/05-local-syslog-input.conf.j2
    owner: logstash
    group: logstash
    mode: 0750
  notify: restart logstash
  when: elk_logstash_local_syslog_input

- name: Configure Logstash | beats-input
  template:
    src: logstash/10-beats-input.conf.j2
    dest: /etc/logstash/conf.d/10-beats-input.conf.j2
    owner: logstash
    group: logstash
    mode: 0750
  notify: restart logstash
  when: elk_logstash_input_beats

- name: Configure Logstash | elasticsearch-output
  template:
    src: logstash/90-elasticsearch-output.conf.j2
    dest: /etc/logstash/conf.d/90-elasticsearch-output.conf.j2
    owner: logstash
    group: logstash
    mode: 0750
  notify: restart logstash
